CC = g++
CFLAGS = -ggdb -ltermbox

main: beatenzone

merge: merge.cpp
	$(CC) $(CFLAGS) merge.cpp -o merge
while: while.cpp
	$(CC) $(CFLAGS) while.cpp -o while
pathfinding: pathfinding.cpp
	$(CC) $(CFLAGS) pathfinding.cpp -o pathfinding
beatenzone: beatenzone.cpp
	$(CC) $(CFLAGS) beatenzone.cpp -o beatenzone
